[versions]
agp = "8.6.0"
core = "1.7.0"
firebaseBom = "34.6.0"
gradlePluginLocal = "1.64.2"
kotlin = "2.1.21"
activityKtx = "1.9.0"
appcompat = "1.6.1"
btt = "2.19.2"
bttFork = "517ad9a1f4"
coilCompose = "2.4.0"
glideCompose = "1.0.0-beta01"
composeBom = "2024.05.00"
constraintlayout = "2.1.4"
converterMoshi = "2.9.0"
coreKtx = "1.13.1"
espressoCore = "3.5.1"
fragmentKtx = "1.7.1"
glide = "4.14.2"
gson = "2.10.1"
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinxCoroutinesCore = "1.8.0"
lifecycleLivedataKtx = "2.8.0"
material = "1.12.0"
materialAndroid = "1.6.7"
navigationCompose = "2.7.7"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
okhttp3Integration = "4.11.0"
okhttpBom = "4.12.0"
retrofitVersion = "2.9.0"
runtimeLivedata = "1.6.7"
safeArgsKotlin = "2.5.3"
activity = "1.9.2"
benchmark = "1.2.4"
runner = "1.5.2"
benchmarkJunit4 = "1.3.4"
clarity = "3.1.3"
speedDial = "3.3.0"
rules = "1.7.0"
uiautomator = "2.2.0"
benchmarkMacroJunit4 = "1.4.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityKtx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleLivedataKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
fork-btt-android-sdk = { module = "com.github.IsmailAloha:btt-android-sdk", version.ref = "bttFork"}
btt-android-sdk = { module = "com.github.blue-triangle-tech:btt-android-sdk", version.ref = "btt" }
coil = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gradle-plugin-local = { module = "com.fullstory:gradle-plugin-local", version.ref = "gradlePluginLocal" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-android = { module = "androidx.compose.material:material-android", version.ref = "materialAndroid" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
speed-dial = { module = "com.leinardi.android:speed-dial", version.ref = "speedDial" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmarkJunit4" }
clarity = { group = "com.microsoft.clarity", name = "clarity", version.ref = "clarity" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeArgsKotlin"}
daggerHiltAndroid = {id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
android-library = { id = "com.android.library", version.ref = "agp" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "agp" }
